import streamlit as st

st.title('🤖 Mahi Lab 🔭🚀')

st.write('Hello world! this is my first streamlit app')
st.info('this is an experiment')
#st.balloons()
#st.snow()
st.toast("Warming up...")
st.error("Error message")
st.button("Done")

st.button("Click me")
#st.download_button("Download file", data)
st.feedback("thumbs")
#st.link_button("Go to gallery", url)
#st.page_link("app.py", label="Home")
#st.data_editor("Edit data", data)
st.checkbox("I agree")
st.toggle("Enable")
st.radio("Pick one", ["cats", "dogs"])
st.selectbox("Pick one", ["cats", "dogs"])
st.multiselect("Buy", ["milk", "apples", "potatoes"])
st.slider("Pick a number", 0, 100)
st.select_slider("Pick a size", ["S", "M", "L"])
st.text_input("First name")
st.number_input("Pick a number", 0, 10)
st.text_area("Text to translate")
st.date_input("Your birthday")
st.time_input("Meeting time")
st.file_uploader("Upload a CSV")
st.camera_input("Take a picture")
st.color_picker("Pick a color")
